import { Student } from './types';

export const MOCK_STUDENTS: Student[] = [
  { name: 'MIGUEL', pokemon: 'charizard', type: 'fire', tasks: [{ name: 'Tarefa 1', score: 0 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 15 }, { name: 'Tarefa 7', score: 40 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 40 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 100 }], totalScore: 270 },
  { name: 'HELLEN', pokemon: 'blastoise', type: 'water', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 15 }, { name: 'Tarefa 7', score: 40 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 30 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 70 }], totalScore: 235 },
  { name: 'CHICO', pokemon: 'wartortle', type: 'water', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 5 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 5 }, { name: 'Tarefa 5', score: 5 }, { name: 'Tarefa 6', score: 5 }, { name: 'Tarefa 7', score: 15 }, { name: 'Tarefa 8', score: 10 }, { name: 'Tarefa 9', score: 20 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 100 }], totalScore: 195 },
  { name: 'LORENA', pokemon: 'venusaur', type: 'grass', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 15 }, { name: 'Tarefa 7', score: 30 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 30 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 90 }], totalScore: 245 },
  { name: 'ADONES', pokemon: 'venusaur', type: 'grass', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 15 }, { name: 'Tarefa 7', score: 30 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 25 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 100 }], totalScore: 250 },
  { name: 'CARLOS', pokemon: 'venusaur', type: 'grass', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 10 }, { name: 'Tarefa 7', score: 40 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 25 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 70 }], totalScore: 225 },
  { name: 'GABRIEL MACHADO', pokemon: 'venusaur', type: 'grass', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 15 }, { name: 'Tarefa 7', score: 30 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 30 }, { name: 'Tarefa 10', score: 16 }, { name: 'Tarefa 11', score: 70 }], totalScore: 221 },
  { name: 'MATHEUS', pokemon: 'charizard', type: 'fire', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 10 }, { name: 'Tarefa 7', score: 30 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 40 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 70 }], totalScore: 230 },
  { name: 'PREFEITO', pokemon: 'charmander', type: 'fire', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 0 }, { name: 'Tarefa 5', score: 0 }, { name: 'Tarefa 6', score: 10 }, { name: 'Tarefa 7', score: 10 }, { name: 'Tarefa 8', score: 10 }, { name: 'Tarefa 9', score: 10 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 10 }], totalScore: 90 },
  { name: 'GDIAS', pokemon: 'charizard', type: 'fire', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 15 }, { name: 'Tarefa 7', score: 30 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 40 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 80 }], totalScore: 245 },
  { name: 'BAGGIO', pokemon: 'charmeleon', type: 'fire', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 10 }, { name: 'Tarefa 7', score: 20 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 30 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 50 }], totalScore: 190 },
  { name: 'EVANDERSON', pokemon: 'blastoise', type: 'water', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 5 }, { name: 'Tarefa 7', score: 40 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 30 }, { name: 'Tarefa 10', score: 18 }, { name: 'Tarefa 11', score: 95 }], totalScore: 248 },
  { name: 'YURI', pokemon: 'charizard', type: 'fire', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 15 }, { name: 'Tarefa 7', score: 30 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 30 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 90 }], totalScore: 245 },
  { name: 'K1', pokemon: 'charmander', type: 'water', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 15 }, { name: 'Tarefa 7', score: 30 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 30 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 95 }], totalScore: 250 },
  { name: 'BOLA', pokemon: 'ivysaur', type: 'grass', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 5 }, { name: 'Tarefa 7', score: 30 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 20 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 35 }], totalScore: 170 },
  { name: 'HELENA', pokemon: 'venusaur', type: 'grass', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 10 }, { name: 'Tarefa 7', score: 40 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 30 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 70 }], totalScore: 230 },
  { name: 'KAIOBA', pokemon: 'bulbasaur', type: 'grass', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 0 }, { name: 'Tarefa 5', score: 0 }, { name: 'Tarefa 6', score: 0 }, { name: 'Tarefa 7', score: 15 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 0 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 10 }], totalScore: 85 },
  { name: 'GALVAO', pokemon: 'blastoise', type: 'water', tasks: [{ name: 'Tarefa 1', score: 0 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 0 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 10 }, { name: 'Tarefa 7', score: 20 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 30 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 90 }], totalScore: 220 },
  { name: 'GABRIEL DA TRUFA', pokemon: 'squirtle', type: 'water', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 0 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 0 }, { name: 'Tarefa 7', score: 10 }, { name: 'Tarefa 8', score: 10 }, { name: 'Tarefa 9', score: 10 }, { name: 'Tarefa 10', score: 10 }, { name: 'Tarefa 11', score: 20 }], totalScore: 90 },
  { name: 'JONATHA', pokemon: 'blastoise', type: 'water', tasks: [{ name: 'Tarefa 1', score: 5 }, { name: 'Tarefa 2', score: 10 }, { name: 'Tarefa 3', score: 5 }, { name: 'Tarefa 4', score: 10 }, { name: 'Tarefa 5', score: 10 }, { name: 'Tarefa 6', score: 15 }, { name: 'Tarefa 7', score: 50 }, { name: 'Tarefa 8', score: 20 }, { name: 'Tarefa 9', score: 30 }, { name: 'Tarefa 10', score: 20 }, { name: 'Tarefa 11', score: 70 }], totalScore: 245 },
];
